# Generated by Django 4.1.2 on 2023-01-06 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginformapp', '0002_userpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='img',
            field=models.ImageField(blank=True, upload_to='userimg/'),
        ),
    ]
